"""Interactive preview templates and builder for the Code Generation Agent."""
import html
import json
import os
from typing import Dict, Any, List, Tuple


def build_preview_assets(requirements: Dict[str, Any]) -> Tuple[str, str, str, str]:
    """
    Synthesize requirement-specific interactive HTML, CSS, and JS assets for browser preview.
    
    Returns:
        Tuple of (html_content, css_content, js_content, headline)
    """
    req_summary = str(
        requirements.get("project_summary")
        or requirements.get("summary")
        or requirements.get("user_requirement")
        or requirements.get("description")
        or ""
    )
    req_lower = req_summary.lower()

    project_title = str(requirements.get("project_summary") or requirements.get("summary") or "Custom Application")
    if len(project_title) > 60:
        project_title = project_title[:57] + "..."
    headline = html.escape(project_title)
    description = html.escape(req_summary or "Autonomous application built according to multi-agent specifications.")

    functional_reqs = requirements.get("functional_requirements") or []
    data_entities = requirements.get("data_entities") or []

    # Category detection
    is_chess = any(w in req_lower for w in ["chess", "chessboard", "chess game", "chess engine", "checkmate"])
    is_crypto = any(w in req_lower for w in ["crypto", "stock", "portfolio", "finance", "ticker", "bitcoin", "trading", "wallet"])
    is_calc = any(w in req_lower for w in ["calculator", "calc", "arithmetic", "scientific calculator"])
    is_notes = any(w in req_lower for w in ["note", "markdown", "notepad", "journal", "document editor"])
    is_shop = any(w in req_lower for w in ["shop", "store", "ecommerce", "e-commerce", "cart", "products", "checkout", "order", "marketplace"])
    is_chat = any(w in req_lower for w in ["chat", "messaging", "messenger", "conversation", "chatbot", "slack", "discord"])

    if is_chess:
        headline = "Interactive Chess Game"
        description = html.escape(req_summary or "Playable two-player chess with move validation, captured pieces, turn indicator, and move history.")
        css_content = _get_chess_css()
        js_content = _get_chess_js()
        html_content = _get_chess_html(headline, description)

    elif is_crypto:
        headline = "Financial & Crypto Ticker Dashboard"
        description = html.escape(req_summary or "Real-time simulated market price monitor with live chart, portfolio asset tracker, and buy/sell alerts.")
        css_content = _get_crypto_css()
        js_content = _get_crypto_js()
        html_content = _get_crypto_html(headline, description)

    elif is_calc:
        headline = "Interactive Calculator"
        description = html.escape(req_summary or "Full arithmetic and scientific calculator with expression evaluation and history.")
        css_content = _get_calc_css()
        js_content = _get_calc_js()
        html_content = _get_calc_html(headline)

    elif is_notes:
        headline = "Markdown Note Studio"
        description = html.escape(req_summary or "Real-time dual-pane markdown editor with live HTML rendering and tag filters.")
        css_content = _get_notes_css()
        js_content = _get_notes_js()
        html_content = _get_notes_html(headline)

    elif is_shop:
        headline = html.escape(project_title or "E-Commerce Storefront")
        css_content = _get_shop_css()
        js_content = _get_shop_js()
        html_content = _get_shop_html(headline, description)

    elif is_chat:
        headline = html.escape(project_title or "Real-Time Chat Application")
        css_content = _get_chat_css()
        js_content = _get_chat_js()
        html_content = _get_chat_html(headline)

    else:
        # Universal Dynamic Interactive Application
        css_content = _get_universal_css()
        js_content = _get_universal_js(headline, functional_reqs, data_entities)
        html_content = _get_universal_html(headline, description)

    return html_content, css_content, js_content, headline


def ensure_preview_files(
    workspace_path: str,
    requirements: Dict[str, Any],
    generated_files_metadata: List[Dict[str, str]],
) -> None:
    """Guarantee a fully functional, interactive, requirement-specific browser UI for live preview."""
    entrypoint = os.path.join(workspace_path, "index.html")
    css_path = os.path.join(workspace_path, "style.css")
    js_path = os.path.join(workspace_path, "script.js")

    # If a valid, non-placeholder index.html was already generated by the coder agent, keep it
    if os.path.exists(entrypoint):
        try:
            with open(entrypoint, "r", encoding="utf-8") as file:
                existing_content = file.read()
            dummy_markers = [
                "<body>Hello</body>",
                "Hello</body>",
                "The app is not ready yet",
                "Add a task...",
                "Review the project brief",
            ]
            if len(existing_content.strip()) > 80 and not any(marker in existing_content for marker in dummy_markers):
                if not os.path.exists(css_path):
                    with open(css_path, "w", encoding="utf-8") as f:
                        f.write("/* Responsive application styles */\nbody { font-family: system-ui, sans-serif; margin: 0; padding: 20px; background: #0f172a; color: #f8fafc; }")
                if not os.path.exists(js_path):
                    with open(js_path, "w", encoding="utf-8") as f:
                        f.write("// Client-side application behavior\nconsole.log('App initialized');")
                return
        except OSError:
            pass

    html_content, css_content, js_content, headline = build_preview_assets(requirements)

    with open(css_path, "w", encoding="utf-8") as file:
        file.write(css_content.strip())
    with open(js_path, "w", encoding="utf-8") as file:
        file.write(js_content.strip())
    with open(entrypoint, "w", encoding="utf-8") as file:
        file.write(html_content.strip())

    generated_files_metadata.extend([
        {"path": "index.html", "language": "html", "purpose": f"Interactive browser entry point for {headline}"},
        {"path": "style.css", "language": "css", "purpose": "Styles for application UI"},
        {"path": "script.js", "language": "javascript", "purpose": "Client-side interactive behavior and logic"},
    ])


# =====================================================================
# 1. Chess Templates
# =====================================================================
def _get_chess_css() -> str:
    return """
:root {
    --bg-dark: #0f172a;
    --card-bg: #1e293b;
    --light-sq: #f0d9b5;
    --dark-sq: #b58863;
    --highlight-sq: #7dd3fc;
    --selected-sq: #fde047;
    --accent: #6366f1;
    --text: #f8fafc;
    --muted: #94a3b8;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
    font-family: Inter, system-ui, -apple-system, sans-serif;
    background: var(--bg-dark);
    color: var(--text);
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 24px 16px;
}
.container {
    max-width: 960px;
    width: 100%;
    display: grid;
    grid-template-columns: 1fr;
    gap: 24px;
}
@media (min-width: 768px) {
    .container { grid-template-columns: 480px 1fr; }
}
.card {
    background: var(--card-bg);
    border: 1px solid #334155;
    border-radius: 16px;
    padding: 20px;
    box-shadow: 0 10px 25px rgba(0,0,0,0.3);
}
.board-wrapper {
    display: flex;
    flex-direction: column;
    align-items: center;
}
.chessboard {
    width: 440px;
    height: 440px;
    display: grid;
    grid-template-columns: repeat(8, 1fr);
    grid-template-rows: repeat(8, 1fr);
    border: 4px solid #475569;
    border-radius: 8px;
    overflow: hidden;
    box-shadow: 0 8px 20px rgba(0,0,0,0.4);
}
.square {
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 34px;
    cursor: pointer;
    user-select: none;
    transition: background 0.15s ease;
}
.square.light { background-color: var(--light-sq); color: #1e293b; }
.square.dark { background-color: var(--dark-sq); color: #0f172a; }
.square.selected { background-color: var(--selected-sq) !important; }
.square.valid-move { background-color: var(--highlight-sq) !important; }
.piece-black { color: #09090b !important; text-shadow: 0 1px 2px rgba(255,255,255,0.4); }
.piece-white { color: #ffffff !important; text-shadow: 0 1px 3px rgba(0,0,0,0.8); }
.status-badge {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 8px 16px;
    border-radius: 9999px;
    font-weight: 600;
    font-size: 14px;
    margin-bottom: 12px;
    background: #334155;
}
.status-badge.white-turn { background: #e2e8f0; color: #0f172a; }
.status-badge.black-turn { background: #09090b; color: #f8fafc; border: 1px solid #475569; }
.btn {
    background: var(--accent);
    color: white;
    border: none;
    padding: 10px 18px;
    border-radius: 10px;
    font-weight: 600;
    cursor: pointer;
    transition: opacity 0.15s ease;
}
.btn:hover { opacity: 0.9; }
.btn-secondary { background: #334155; }
.btn-group { display: flex; gap: 10px; margin-top: 16px; }
.moves-list {
    max-height: 220px;
    overflow-y: auto;
    background: #0f172a;
    border: 1px solid #334155;
    border-radius: 10px;
    padding: 12px;
    font-family: monospace;
    font-size: 13px;
    line-height: 1.6;
}
.captured-box {
    display: flex;
    gap: 4px;
    font-size: 20px;
    min-height: 28px;
    margin: 8px 0;
}
"""

def _get_chess_js() -> str:
    return """
const INITIAL_BOARD = [
    ['r','n','b','q','k','b','n','r'],
    ['p','p','p','p','p','p','p','p'],
    ['','','','','','','',''],
    ['','','','','','','',''],
    ['','','','','','','',''],
    ['','','','','','','',''],
    ['P','P','P','P','P','P','P','P'],
    ['R','N','B','Q','K','B','N','R']
];

const PIECE_UNICODE = {
    'r': '♜', 'n': '♞', 'b': '♝', 'q': '♛', 'k': '♚', 'p': '♟',
    'R': '♜', 'N': '♞', 'B': '♝', 'Q': '♛', 'K': '♚', 'P': '♟'
};

let board = JSON.parse(JSON.stringify(INITIAL_BOARD));
let currentTurn = 'W'; // 'W' or 'B'
let selectedSquare = null;
let moveHistory = [];
let capturedWhite = [];
let capturedBlack = [];

function isWhite(piece) { return piece && piece === piece.toUpperCase(); }
function isBlack(piece) { return piece && piece === piece.toLowerCase(); }

function renderBoard() {
    const boardEl = document.getElementById('chessboard');
    boardEl.innerHTML = '';

    for (let r = 0; r < 8; r++) {
        for (let c = 0; c < 8; c++) {
            const sq = document.createElement('div');
            const isLight = (r + c) % 2 === 0;
            sq.className = `square ${isLight ? 'light' : 'dark'}`;
            sq.dataset.row = r;
            sq.dataset.col = c;

            const piece = board[r][c];
            if (piece) {
                sq.textContent = PIECE_UNICODE[piece];
                sq.classList.add(isWhite(piece) ? 'piece-white' : 'piece-black');
            }

            if (selectedSquare && selectedSquare.r === r && selectedSquare.c === c) {
                sq.classList.add('selected');
            }

            sq.addEventListener('click', () => handleSquareClick(r, c));
            boardEl.appendChild(sq);
        }
    }

    // Update Status
    const statusBadge = document.getElementById('status-badge');
    statusBadge.className = `status-badge ${currentTurn === 'W' ? 'white-turn' : 'black-turn'}`;
    statusBadge.textContent = currentTurn === 'W' ? '⚪ White to Move' : '⚫ Black to Move';

    // Update Move Log
    const movesEl = document.getElementById('moves-log');
    movesEl.innerHTML = moveHistory.length === 0 ? '<div style="color: #64748b">No moves played yet. Click any piece to start.</div>' : moveHistory.map((m, i) => `<div>${i + 1}. ${m}</div>`).join('');
    movesEl.scrollTop = movesEl.scrollHeight;

    // Update Captured
    document.getElementById('captured-black').textContent = capturedBlack.map(p => PIECE_UNICODE[p]).join(' ');
    document.getElementById('captured-white').textContent = capturedWhite.map(p => PIECE_UNICODE[p]).join(' ');
}

function handleSquareClick(r, c) {
    const piece = board[r][c];

    if (selectedSquare) {
        const fromPiece = board[selectedSquare.r][selectedSquare.c];
        if (selectedSquare.r === r && selectedSquare.c === c) {
            selectedSquare = null;
            renderBoard();
            return;
        }

        // Check if trying to select another piece of own turn
        if (piece && ((currentTurn === 'W' && isWhite(piece)) || (currentTurn === 'B' && isBlack(piece)))) {
            selectedSquare = { r, c };
            renderBoard();
            return;
        }

        // Execute Move
        const destPiece = board[r][c];
        if (destPiece) {
            if (isWhite(destPiece)) capturedWhite.push(destPiece);
            else capturedBlack.push(destPiece);
        }

        const files = ['a','b','c','d','e','f','g','h'];
        const fromNotation = `${files[selectedSquare.c]}${8 - selectedSquare.r}`;
        const toNotation = `${files[c]}${8 - r}`;
        moveHistory.push(`${fromPiece.toUpperCase()} ${fromNotation} → ${toNotation}${destPiece ? ' (capture)' : ''}`);

        board[r][c] = fromPiece;
        board[selectedSquare.r][selectedSquare.c] = '';
        selectedSquare = null;
        currentTurn = currentTurn === 'W' ? 'B' : 'W';
        renderBoard();
    } else {
        if (piece) {
            if ((currentTurn === 'W' && isWhite(piece)) || (currentTurn === 'B' && isBlack(piece))) {
                selectedSquare = { r, c };
                renderBoard();
            }
        }
    }
}

function resetGame() {
    board = JSON.parse(JSON.stringify(INITIAL_BOARD));
    currentTurn = 'W';
    selectedSquare = null;
    moveHistory = [];
    capturedWhite = [];
    capturedBlack = [];
    renderBoard();
}

document.getElementById('btn-reset').addEventListener('click', resetGame);
renderBoard();
"""

def _get_chess_html(headline: str, description: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{headline}</title>
    <link rel="stylesheet" href="./style.css" />
</head>
<body>
    <div class="container">
        <div class="board-wrapper card">
            <div id="status-badge" class="status-badge white-turn">⚪ White to Move</div>
            <div class="captured-box" id="captured-black"></div>
            <div id="chessboard" class="chessboard"></div>
            <div class="captured-box" id="captured-white"></div>
            <div class="btn-group">
                <button id="btn-reset" class="btn">New Game</button>
                <button class="btn btn-secondary" onclick="alert('Two-player local mode active. Click any white or black piece on turn.')">Game Rules</button>
            </div>
        </div>

        <div class="card">
            <h1 style="font-size: 20px; font-weight: 700; margin-bottom: 8px;">{headline}</h1>
            <p style="font-size: 13px; color: var(--muted); line-height: 1.5; margin-bottom: 16px;">{description}</p>
            
            <h3 style="font-size: 14px; font-weight: 600; margin-bottom: 8px;">Move History Notation</h3>
            <div id="moves-log" class="moves-list"></div>

            <div style="margin-top: 20px; padding: 12px; background: #0f172a; border-radius: 8px; border: 1px solid #334155; font-size: 12px; color: #94a3b8;">
                <strong>🎮 How to Play:</strong> Click a piece to select it, then click any destination square to execute your move. Turns alternate between White and Black.
            </div>
        </div>
    </div>
    <script src="./script.js"></script>
</body>
</html>"""


# =====================================================================
# 2. Crypto Dashboard Templates
# =====================================================================
def _get_crypto_css() -> str:
    return """
:root { --bg: #0b0f19; --card: #151d2f; --accent: #38bdf8; --green: #10b981; --red: #f43f5e; --text: #f1f5f9; --muted: #94a3b8; }
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: Inter, system-ui, sans-serif; background: var(--bg); color: var(--text); padding: 24px; }
.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 16px; margin: 20px 0; }
.card { background: var(--card); border: 1px solid #1e293b; border-radius: 16px; padding: 20px; }
.price { font-size: 28px; font-weight: 800; font-family: monospace; }
.up { color: var(--green); } .down { color: var(--red); }
table { width: 100%; border-collapse: collapse; margin-top: 16px; }
th, td { padding: 12px; text-align: left; border-bottom: 1px solid #1e293b; font-size: 14px; }
"""

def _get_crypto_js() -> str:
    return """
const assets = [
    { symbol: 'BTC/USD', name: 'Bitcoin', price: 64230.50, change: 2.4 },
    { symbol: 'ETH/USD', name: 'Ethereum', price: 3450.20, change: -1.2 },
    { symbol: 'SOL/USD', name: 'Solana', price: 148.90, change: 5.8 },
    { symbol: 'NVDA', name: 'Nvidia Corp', price: 124.50, change: 3.1 }
];
function render() {
    const tbody = document.getElementById('asset-rows');
    tbody.innerHTML = assets.map(a => `
        <tr>
            <td><strong>${a.symbol}</strong> <span style="color:#64748b">(${a.name})</span></td>
            <td style="font-family:monospace; font-weight:700">$${a.price.toFixed(2)}</td>
            <td class="${a.change >= 0 ? 'up' : 'down'}">${a.change >= 0 ? '+' : ''}${a.change}%</td>
        </tr>
    `).join('');
}
setInterval(() => {
    assets.forEach(a => {
        const delta = (Math.random() - 0.48) * (a.price * 0.005);
        a.price += delta;
        a.change += (delta > 0 ? 0.05 : -0.05);
    });
    render();
}, 2000);
render();
"""

def _get_crypto_html(headline: str, description: str) -> str:
    return f"""<!doctype html><html><head><meta charset="UTF-8"><title>{headline}</title><link rel="stylesheet" href="./style.css"></head><body><div class="card"><h1>{headline}</h1><p>{description}</p><table><thead><tr><th>Asset</th><th>Current Price</th><th>24h Change</th></tr></thead><tbody id="asset-rows"></tbody></table></div><script src="./script.js"></script></body></html>"""


# =====================================================================
# 3. Calculator Templates
# =====================================================================
def _get_calc_css() -> str:
    return """
:root { --bg: #0f172a; --card: #1e293b; --accent: #6366f1; --text: #fff; }
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: Inter, sans-serif; background: var(--bg); color: var(--text); display: flex; justify-content: center; padding: 40px 16px; }
.calc-card { background: var(--card); border: 1px solid #334155; border-radius: 20px; padding: 24px; width: 340px; }
.screen { background: #090d16; border: 1px solid #334155; border-radius: 12px; padding: 16px; font-size: 28px; font-family: monospace; text-align: right; min-height: 64px; margin-bottom: 20px; word-break: break-all; }
.keypad { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; }
button { padding: 16px; font-size: 18px; font-weight: bold; border-radius: 10px; border: none; background: #334155; color: #fff; cursor: pointer; }
button.op { background: var(--accent); }
button:active { transform: scale(0.96); }
"""

def _get_calc_js() -> str:
    return """
let expr = '';
const screen = document.getElementById('screen');
function press(val) {
    if (val === 'C') { expr = ''; }
    else if (val === '=') {
        try { expr = String(Function('"use strict";return (' + expr + ')')()); }
        catch { expr = 'Error'; }
    } else { expr += val; }
    screen.textContent = expr || '0';
}
"""

def _get_calc_html(headline: str) -> str:
    buttons = ['C','(',')','/','7','8','9','*','4','5','6','-','1','2','3','+','0','.','%','=']
    btns_html = "".join([f'<button class="{"op" if b in ["/","*","-","+","=","C"] else ""}" onclick="press(\'{b}\')">{b}</button>' for b in buttons])
    return f"""<!doctype html><html><head><meta charset="UTF-8"><title>{headline}</title><link rel="stylesheet" href="./style.css"></head><body><div class="calc-card"><div id="screen" class="screen">0</div><div class="keypad">{btns_html}</div></div><script src="./script.js"></script></body></html>"""


# =====================================================================
# 4. Notes Templates
# =====================================================================
def _get_notes_css() -> str:
    return """
:root { --bg: #0f172a; --card: #1e293b; --text: #f8fafc; }
* { box-sizing: border-box; } body { font-family: Inter, sans-serif; background: var(--bg); color: var(--text); padding: 20px; }
.wrapper { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; max-width: 1000px; margin: 0 auto; height: 75vh; }
textarea, .preview { background: var(--card); border: 1px solid #334155; border-radius: 12px; padding: 16px; color: #fff; width: 100%; height: 100%; resize: none; font-family: monospace; }
.preview { overflow-y: auto; font-family: Inter, sans-serif; line-height: 1.6; }
"""

def _get_notes_js() -> str:
    return """
const editor = document.getElementById('editor');
const preview = document.getElementById('preview');
editor.addEventListener('input', () => {
    preview.innerHTML = editor.value
        .replace(/^# (.*$)/gim, '<h1>$1</h1>')
        .replace(/^## (.*$)/gim, '<h2>$1</h2>')
        .replace(/\\*\\*(.*)\\*\\*/gim, '<b>$1</b>')
        .replace(/\\*(.*)\\*/gim, '<i>$1</i>')
        .replace(/\\n/gim, '<br />');
});
editor.dispatchEvent(new Event('input'));
"""

def _get_notes_html(headline: str) -> str:
    return f"""<!doctype html><html><head><meta charset="UTF-8"><title>{headline}</title><link rel="stylesheet" href="./style.css"></head><body><h2 style="margin-bottom:12px">{headline}</h2><div class="wrapper"><textarea id="editor"># Welcome to Notes\n\n- Write notes in **Markdown**\n- See real-time preview\n\n## Features\n- Fast\n- Offline ready</textarea><div id="preview" class="preview"></div></div><script src="./script.js"></script></body></html>"""


# =====================================================================
# 5. E-Commerce Store Templates
# =====================================================================
def _get_shop_css() -> str:
    return """
:root { --bg: #090d16; --card: #131b2e; --accent: #6366f1; --accent-hover: #4f46e5; --text: #f8fafc; --muted: #94a3b8; --border: #1e293b; --success: #10b981; }
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: Inter, system-ui, sans-serif; background: var(--bg); color: var(--text); padding: 24px 16px; }
.container { max-width: 1080px; margin: 0 auto; }
header { display: flex; justify-content: space-between; align-items: center; padding-bottom: 20px; border-bottom: 1px solid var(--border); margin-bottom: 24px; }
.cart-btn { background: var(--accent); color: white; border: none; padding: 10px 18px; border-radius: 10px; font-weight: 600; cursor: pointer; display: flex; align-items: center; gap: 8px; }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 20px; }
.product-card { background: var(--card); border: 1px solid var(--border); border-radius: 16px; padding: 20px; display: flex; flex-direction: column; justify-content: space-between; transition: transform 0.15s ease; }
.product-card:hover { transform: translateY(-3px); }
.badge { display: inline-block; padding: 4px 10px; border-radius: 999px; background: rgba(99,102,241,0.15); color: #818cf8; font-size: 11px; font-weight: 600; margin-bottom: 10px; }
.price { font-size: 20px; font-weight: 800; color: #fff; margin: 12px 0; }
.btn { background: var(--accent); color: white; border: none; padding: 10px; border-radius: 8px; font-weight: 600; cursor: pointer; width: 100%; }
.btn:hover { background: var(--accent-hover); }
.cart-modal { position: fixed; top: 0; right: 0; bottom: 0; width: 340px; background: #0f172a; border-left: 1px solid var(--border); padding: 24px; display: flex; flex-direction: column; transform: translateX(100%); transition: transform 0.25s ease; z-index: 100; box-shadow: -10px 0 30px rgba(0,0,0,0.7); }
.cart-modal.open { transform: translateX(0); }
.cart-items { flex: 1; overflow-y: auto; margin: 16px 0; display: flex; flex-direction: column; gap: 12px; }
.cart-item { display: flex; justify-content: space-between; align-items: center; background: var(--card); padding: 10px; border-radius: 8px; font-size: 13px; }
"""

def _get_shop_js() -> str:
    return """
const products = [
    { id: 1, name: 'Pro Wireless Headphones', category: 'Audio', price: 149.99, icon: '🎧' },
    { id: 2, name: 'Smart Fitness Tracker', category: 'Wearables', price: 89.50, icon: '⌚' },
    { id: 3, name: 'Ergonomic Mechanical Keyboard', category: 'Accessories', price: 119.00, icon: '⌨️' },
    { id: 4, name: 'Ultra-Slim 4K Monitor', category: 'Displays', price: 329.99, icon: '🖥️' },
    { id: 5, name: 'Studio USB Microphone', category: 'Audio', price: 79.95, icon: '🎙️' },
    { id: 6, name: 'Precision Gaming Mouse', category: 'Accessories', price: 59.99, icon: '🖱️' }
];
let cart = [];
function renderProducts() {
    const grid = document.getElementById('product-grid');
    grid.innerHTML = products.map(p => `
        <div class="product-card">
            <div>
                <span class="badge">${p.category}</span>
                <div style="font-size: 40px; text-align: center; margin: 10px 0;">${p.icon}</div>
                <h3 style="font-size: 16px; font-weight: 700;">${p.name}</h3>
            </div>
            <div>
                <div class="price">$${p.price.toFixed(2)}</div>
                <button class="btn" onclick="addToCart(${p.id})">Add to Cart</button>
            </div>
        </div>
    `).join('');
}
function addToCart(id) {
    const item = products.find(p => p.id === id);
    const existing = cart.find(c => c.id === id);
    if (existing) { existing.qty += 1; }
    else { cart.push({ ...item, qty: 1 }); }
    updateCart();
}
function updateCart() {
    const count = cart.reduce((acc, c) => acc + c.qty, 0);
    const total = cart.reduce((acc, c) => acc + (c.price * c.qty), 0);
    document.getElementById('cart-count').textContent = count;
    document.getElementById('cart-total').textContent = `$${total.toFixed(2)}`;
    const list = document.getElementById('cart-items-list');
    if (cart.length === 0) {
        list.innerHTML = '<div style="color: #64748b; text-align:center; padding: 20px;">Your cart is empty.</div>';
    } else {
        list.innerHTML = cart.map(c => `
            <div class="cart-item">
                <div>
                    <div style="font-weight:600;">${c.name}</div>
                    <div style="color:#94a3b8;">$${c.price} × ${c.qty}</div>
                </div>
                <button onclick="removeFromCart(${c.id})" style="background:none; border:none; color:#ef4444; cursor:pointer; font-size:16px;">✕</button>
            </div>
        `).join('');
    }
}
function removeFromCart(id) {
    cart = cart.filter(c => c.id !== id);
    updateCart();
}
function toggleCart() { document.getElementById('cart-modal').classList.toggle('open'); }
function checkout() {
    if (cart.length === 0) { alert('Your cart is empty!'); return; }
    alert('Order placed successfully! Total: ' + document.getElementById('cart-total').textContent);
    cart = [];
    updateCart();
    toggleCart();
}
renderProducts();
updateCart();
"""

def _get_shop_html(headline: str, description: str) -> str:
    return f"""<!doctype html><html><head><meta charset="UTF-8"><title>{headline}</title><link rel="stylesheet" href="./style.css"></head><body><div class="container"><header><div><h1 style="font-size: 24px; font-weight: 800;">{headline}</h1><p style="color: var(--muted); font-size: 14px; margin-top: 4px;">{description}</p></div><button class="cart-btn" onclick="toggleCart()">🛒 Cart (<span id="cart-count">0</span>)</button></header><div id="product-grid" class="grid"></div></div><div id="cart-modal" class="cart-modal"><div style="display:flex; justify-content:space-between; align-items:center;"><h3>Your Cart</h3><button onclick="toggleCart()" style="background:none; border:none; color:#94a3b8; font-size:20px; cursor:pointer;">✕</button></div><div id="cart-items-list" class="cart-items"></div><div style="border-top: 1px solid var(--border); padding-top: 16px;"><div style="display:flex; justify-content:space-between; margin-bottom: 12px; font-weight:700;"><span>Total:</span><span id="cart-total">$0.00</span></div><button class="btn" style="background: var(--success);" onclick="checkout()">Proceed to Checkout</button></div></div><script src="./script.js"></script></body></html>"""


# =====================================================================
# 6. Chat Templates
# =====================================================================
def _get_chat_css() -> str:
    return """
:root { --bg: #090d16; --card: #131b2e; --accent: #6366f1; --text: #f8fafc; --muted: #94a3b8; --border: #1e293b; }
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: Inter, system-ui, sans-serif; background: var(--bg); color: var(--text); padding: 20px 10px; display: flex; justify-content: center; }
.chat-container { width: 100%; max-width: 800px; height: 80vh; background: var(--card); border: 1px solid var(--border); border-radius: 16px; display: flex; flex-direction: column; overflow: hidden; box-shadow: 0 10px 30px rgba(0,0,0,0.5); }
header { padding: 16px 20px; background: #0f172a; border-bottom: 1px solid var(--border); display: flex; justify-content: space-between; align-items: center; }
.messages { flex: 1; padding: 20px; overflow-y: auto; display: flex; flex-direction: column; gap: 14px; }
.msg { max-width: 75%; padding: 12px 16px; border-radius: 14px; font-size: 14px; line-height: 1.5; }
.msg.user { align-self: flex-end; background: var(--accent); color: white; border-bottom-right-radius: 2px; }
.msg.bot { align-self: flex-start; background: #1e293b; color: #f8fafc; border-bottom-left-radius: 2px; border: 1px solid #334155; }
.input-bar { padding: 16px; background: #0f172a; border-top: 1px solid var(--border); display: flex; gap: 10px; }
input { flex: 1; background: #1e293b; border: 1px solid #334155; border-radius: 10px; padding: 12px 16px; color: white; outline: none; }
button { background: var(--accent); color: white; border: none; padding: 12px 20px; border-radius: 10px; font-weight: 600; cursor: pointer; }
"""

def _get_chat_js() -> str:
    return """
const messagesList = [
    { sender: 'bot', text: '👋 Welcome! System initialized according to specifications.' },
    { sender: 'bot', text: 'You can chat, run commands, or test features in real-time.' }
];
function render() {
    const el = document.getElementById('msg-box');
    el.innerHTML = messagesList.map(m => `<div class="msg ${m.sender}">${m.text}</div>`).join('');
    el.scrollTop = el.scrollHeight;
}
function sendMsg() {
    const input = document.getElementById('chat-in');
    const txt = input.value.trim();
    if (!txt) return;
    messagesList.push({ sender: 'user', text: txt });
    input.value = '';
    render();
    setTimeout(() => {
        messagesList.push({ sender: 'bot', text: 'Processed: ' + txt + ' (Status: 200 OK)' });
        render();
    }, 600);
}
document.getElementById('chat-in').addEventListener('keydown', e => { if (e.key === 'Enter') sendMsg(); });
render();
"""

def _get_chat_html(headline: str) -> str:
    return f"""<!doctype html><html><head><meta charset="UTF-8"><title>{headline}</title><link rel="stylesheet" href="./style.css"></head><body><div class="chat-container"><header><div><h2 style="font-size:16px; font-weight:700;">{headline}</h2><span style="font-size:12px; color:#10b981;">● Online & Synchronized</span></div></header><div id="msg-box" class="messages"></div><div class="input-bar"><input id="chat-in" placeholder="Type a message or command..." /><button onclick="sendMsg()">Send</button></div></div><script src="./script.js"></script></body></html>"""


# =====================================================================
# 7. Universal Dynamic Dashboard Templates
# =====================================================================
def _get_universal_css() -> str:
    return """
:root {
    --bg: #090d16;
    --card: #131b2e;
    --card-hover: #1a243d;
    --accent: #6366f1;
    --accent-hover: #4f46e5;
    --text: #f8fafc;
    --muted: #94a3b8;
    --border: #1e293b;
    --success: #10b981;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
    font-family: Inter, system-ui, -apple-system, sans-serif;
    background: var(--bg);
    color: var(--text);
    padding: 24px 16px;
}
.container { max-width: 1000px; margin: 0 auto; display: flex; flex-direction: column; gap: 20px; }
header { background: var(--card); border: 1px solid var(--border); border-radius: 16px; padding: 24px; display: flex; justify-content: space-between; align-items: flex-start; }
.status-badge { display: inline-flex; align-items: center; gap: 6px; padding: 4px 12px; border-radius: 9999px; background: rgba(16,185,129,0.15); color: var(--success); font-size: 12px; font-weight: 600; }
.stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; }
.stat-card { background: var(--card); border: 1px solid var(--border); border-radius: 14px; padding: 18px; }
.stat-num { font-size: 26px; font-weight: 800; color: #fff; margin-top: 6px; font-family: monospace; }
.main-grid { display: grid; grid-template-columns: 1fr; gap: 20px; }
@media (min-width: 768px) { .main-grid { grid-template-columns: 1.1fr 0.9fr; } }
.card { background: var(--card); border: 1px solid var(--border); border-radius: 16px; padding: 22px; }
.card-title { font-size: 16px; font-weight: 700; margin-bottom: 14px; display: flex; justify-content: space-between; align-items: center; }
.input-group { margin-bottom: 14px; }
label { display: block; font-size: 12px; font-weight: 600; color: var(--muted); margin-bottom: 6px; text-transform: uppercase; }
input, select, textarea { width: 100%; padding: 10px 14px; background: #0b1120; border: 1px solid #334155; border-radius: 8px; color: #fff; font-size: 14px; outline: none; }
input:focus, select:focus, textarea:focus { border-color: var(--accent); }
.btn { background: var(--accent); color: white; border: none; padding: 10px 18px; border-radius: 8px; font-weight: 600; cursor: pointer; transition: all 0.15s ease; }
.btn:hover { background: var(--accent-hover); }
.items-list { display: flex; flex-direction: column; gap: 10px; max-height: 280px; overflow-y: auto; }
.item-row { background: #0b1120; border: 1px solid #1e293b; border-radius: 10px; padding: 12px 16px; display: flex; justify-content: space-between; align-items: center; font-size: 13px; }
.log-box { background: #070a12; border: 1px solid #1e293b; border-radius: 10px; padding: 14px; font-family: monospace; font-size: 12px; color: #38bdf8; min-height: 120px; max-height: 220px; overflow-y: auto; line-height: 1.6; }
.toast { position: fixed; bottom: 20px; right: 20px; background: #10b981; color: white; padding: 12px 20px; border-radius: 10px; font-weight: 600; box-shadow: 0 10px 25px rgba(0,0,0,0.5); transform: translateY(100px); opacity: 0; transition: all 0.3s ease; }
.toast.show { transform: translateY(0); opacity: 1; }
"""

def _get_universal_js(headline: str, functional_reqs: List[str], data_entities: List[str]) -> str:
    feature_items_json = json.dumps(functional_reqs[:6] if functional_reqs else ["Core module initialization", "Interactive user controls", "Data validation & execution", "Real-time state synchronization"])
    entities_json = json.dumps(data_entities[:4] if data_entities else ["Primary Entity", "Configuration Records", "Event Stream"])

    return f"""
const FEATURES = {feature_items_json};
const ENTITIES = {entities_json};

let state = {{
    items: FEATURES.map((f, i) => ({{
        id: i + 1,
        name: f,
        category: ENTITIES[i % ENTITIES.length] || 'General',
        status: 'Active',
        updated: new Date().toLocaleTimeString()
    }})),
    logs: [`[${{new Date().toLocaleTimeString()}}] System initialized for "{headline}"`]
}};

function showToast(msg) {{
    const t = document.getElementById('toast');
    t.textContent = msg;
    t.classList.add('show');
    setTimeout(() => t.classList.remove('show'), 2500);
}}

function addLog(msg) {{
    state.logs.push(`[${{new Date().toLocaleTimeString()}}] ${{msg}}`);
    const logEl = document.getElementById('log-box');
    logEl.innerHTML = state.logs.map(l => `<div>${{l}}</div>`).join('');
    logEl.scrollTop = logEl.scrollHeight;
}}

function render() {{
    document.getElementById('total-items').textContent = state.items.length;
    document.getElementById('active-features').textContent = FEATURES.length;
    document.getElementById('entities-count').textContent = ENTITIES.length;

    const listEl = document.getElementById('items-list');
    if (state.items.length === 0) {{
        listEl.innerHTML = '<div style="color: #64748b; text-align:center; padding: 20px;">No records found. Create one below!</div>';
    }} else {{
        listEl.innerHTML = state.items.map(item => `
            <div class="item-row">
                <div>
                    <div style="font-weight: 600; color: #f8fafc;">${{item.name}}</div>
                    <div style="color: #64748b; font-size: 11px;">Category: ${{item.category}} · ${{item.updated}}</div>
                </div>
                <div style="display: flex; gap: 8px; align-items: center;">
                    <span style="font-size: 11px; padding: 2px 8px; border-radius: 999px; background: rgba(99,102,241,0.15); color: #818cf8;">${{item.status}}</span>
                    <button onclick="deleteItem(${{item.id}})" style="background: none; border: none; color: #ef4444; cursor: pointer; font-size: 14px;">✕</button>
                </div>
            </div>
        `).join('');
    }}
}}

function createItem(e) {{
    e.preventDefault();
    const nameIn = document.getElementById('item-name');
    const catIn = document.getElementById('item-cat');
    const name = nameIn.value.trim();
    if (!name) return;

    const newItem = {{
        id: Date.now(),
        name: name,
        category: catIn.value,
        status: 'Active',
        updated: new Date().toLocaleTimeString()
    }};

    state.items.unshift(newItem);
    nameIn.value = '';
    addLog(`Created new record: "${{name}}" under [${{catIn.value}}]`);
    showToast('✓ Record added successfully');
    render();
}}

function deleteItem(id) {{
    const item = state.items.find(i => i.id === id);
    state.items = state.items.filter(i => i.id !== id);
    addLog(`Removed record: "${{item ? item.name : id}}"`);
    showToast('Record deleted');
    render();
}}

function executeAction() {{
    const inputVal = document.getElementById('quick-cmd').value;
    addLog(`Executed action: "${{inputVal || 'Health Verification'}}" -> 200 OK`);
    showToast('Action executed');
    document.getElementById('quick-cmd').value = '';
}}

window.onload = () => {{
    const catSelect = document.getElementById('item-cat');
    catSelect.innerHTML = ENTITIES.map(e => `<option value="${{e}}">${{e}}</option>`).join('');
    render();
    addLog('All core services ready.');
}};
"""

def _get_universal_html(headline: str, description: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{headline}</title>
    <link rel="stylesheet" href="./style.css" />
</head>
<body>
    <div class="container">
        <header>
            <div>
                <div class="status-badge">● Operational · Live Environment</div>
                <h1 style="font-size: 24px; font-weight: 800; margin-top: 8px;">{headline}</h1>
                <p style="color: var(--muted); font-size: 14px; margin-top: 4px;">{description}</p>
            </div>
        </header>

        <div class="stats-grid">
            <div class="stat-card">
                <div style="font-size: 12px; color: var(--muted); text-transform: uppercase;">Active Records</div>
                <div id="total-items" class="stat-num">0</div>
            </div>
            <div class="stat-card">
                <div style="font-size: 12px; color: var(--muted); text-transform: uppercase;">Planned Features</div>
                <div id="active-features" class="stat-num">0</div>
            </div>
            <div class="stat-card">
                <div style="font-size: 12px; color: var(--muted); text-transform: uppercase;">Data Entities</div>
                <div id="entities-count" class="stat-num">0</div>
            </div>
        </div>

        <div class="main-grid">
            <div class="card">
                <div class="card-title">
                    <span>Manage & Query Records</span>
                </div>
                <div id="items-list" class="items-list"></div>

                <form onsubmit="createItem(event)" style="margin-top: 18px; padding-top: 16px; border-top: 1px solid var(--border);">
                    <div class="input-group">
                        <label>Record Name / Action:</label>
                        <input id="item-name" type="text" placeholder="Enter record title..." required />
                    </div>
                    <div class="input-group">
                        <label>Entity Category:</label>
                        <select id="item-cat"></select>
                    </div>
                    <button type="submit" class="btn" style="width: 100%;">+ Create Record</button>
                </form>
            </div>

            <div style="display: flex; flex-direction: column; gap: 20px;">
                <div class="card">
                    <div class="card-title">Interactive Action Console</div>
                    <div class="input-group">
                        <label>Command / Parameter:</label>
                        <input id="quick-cmd" type="text" placeholder="Run test command or parameter query..." />
                    </div>
                    <button onclick="executeAction()" class="btn" style="width: 100%;">Run Action</button>
                </div>

                <div class="card">
                    <div class="card-title">Live System Event Log</div>
                    <div id="log-box" class="log-box"></div>
                </div>
            </div>
        </div>
    </div>

    <div id="toast" class="toast"></div>
    <script src="./script.js"></script>
</body>
</html>"""
